In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('emissions.csv')
df.describe()

,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,cloud_provider,cloud_region,cpu_count,gpu_count,longitude,latitude,ram_total_size
count,580.000000,580.000000,5.800000e+02,580.000000,580.000000,580.000000,580.000000,580.000000,580.000000,580.000000,0.0,0.0,580.0,580.0,5.800000e+02,5.800000e+02,580.000000
mean,53.855120,0.000087,2.903766e-06,252.709916,86.465819,141.196921,0.000520,0.000159,0.000273,0.000952,NaN,NaN,128.0,2.0,1.415130e+01,4.656370e+01,376.525124
std,30.209523,0.000017,3.180059e-06,59.182089,73.517080,0.000000,0.000055,0.000116,0.000056,0.000188,NaN,NaN,0.0,0.0,2.169026e-13,3.271318e-13,0.000000
min,6.497416,0.000058,5.568288e-07,185.359283,54.615000,141.196921,0.000454,0.000049,0.000121,0.000640,NaN,NaN,128.0,2.0,1.415130e+01,4.656370e+01,376.525124
25%,28.893607,0.000079,1.031023e-06,235.980092,54.812000,141.196921,0.000483,0.000104,0.000262,0.000863,NaN,NaN,128.0,2.0,1.415130e+01,4.656370e+01,376.525124
50%,51.795763,0.000081,1.675974e-06,253.008262,54.917000,141.196921,0.000504,0.000109,0.000275,0.000889,NaN,NaN,128.0,2.0,1.415130e+01,4.656370e+01,376.525124
75%,77.784130,0.000086,3.211182e-06,260.123259,56.000500,141.196921,0.000536,0.000134,0.000283,0.000949,NaN,NaN,128.0,2.0,1.415130e+01,4.656370e+01,376.525124
max,111.493501,0.000136,1.778298e-05,634.536511,391.585000,141.196921,0.000671,0.000532,0.000552,0.001499,NaN,NaN,128.0,2.0,1.415130e+01,4.656370e+01,376.525124

In [29]:
# df['project_name'][df['project_name'].apply(lambda x: not x.endswith('_gpu2'))] += '_gpu2'
df.describe()
df.to_csv('emissions.csv')

In [59]:
df['project_name'] = df['project_name'].apply(lambda x: x.split('_')[0].removesuffix('s'))

In [60]:
agg = df.groupby(df['project_name']).aggregate({'energy_consumed': 'mean'})

In [61]:
agg.sort_values(by='project_name')

              energy_consumed
project_name
0.125                0.000775
0.25                 0.000859
0.5                  0.000875
0.75                 0.000902
1.0                  0.000942
1.25                 0.001069
1.5                  0.001025
1.75                 0.001024
10.0                 0.000844
11.0                 0.000914
12.0                 0.000892
13.0                 0.000888
14.0                 0.000924
15.0                 0.000882
16.0                 0.000915
17.0                 0.000865
18.0                 0.000879
19.0                 0.000871
2.0                  0.001038
2.25                 0.001164
2.5                  0.000954
2.75                 0.001079
20.0                 0.000880
3.0                  0.001072
4.0                  0.000889
5.0                  0.000899
6.0                  0.000888
7.0                  0.001276
8.0                  0.000917
9.0                  0.000904